### PR TITLE
Add package description

### PR DESCRIPTION
**Pull request by jrgnicho**
Addresses the catkin_lint warnings mentioned in #2

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@jrgnicho: looks like you used an email address that GH doesn't know about, so this commit isn't attributed to your account.

Would you wan to fix that before we merge?

**Comment by jrgnicho** [comment]
@gavanderhoorn good catch, yes I'll change it.

**Comment by jrgnicho** [comment]
@gavanderhoorn I made the correction.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks for the update @jrgnicho :+1:

**Pull request merged**
