### PR TITLE
Switch to Github Actions for CI

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Still using `industrial_ci`, but now hosted by Github Actions.

Fairly minimal `matrix` build of Melodic and Noetic on Bionic and Focal. Might add Xenial+Kinetic back later (for Ubuntu ESM).

Runs here: [gavanderhoorn/stomp_ros/actions](https://github.com/gavanderhoorn/stomp_ros/actions).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
For https://github.com/ros-industrial/ros_industrial_issues/issues/74

**Comment by gavanderhoorn** [comment]
CI is green, runs were successful.

Converting to PR.

**Comment by gavanderhoorn** [comment]
1c1d6e3 works around a known issue in Trac IK. See https://bitbucket.org/traclabs/trac_ik/issues/72/noetic-nlopt-cxx-dev-should-be-a for more information.

Thanks to @fmauch for reporting it and getting the fix merged (now we only need a new release).

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
thanks for the review @Levi-Armstrong

**Pull request merged**
