### PR TITLE
Remove stomp_core package and leverage stomp cmake package

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
The stomp_core package has been moved to the [stomp](https://github.com/ros-industrial/stomp.git) repository which is now independent of ROS.

It has also been renamed to stomp instead of stomp_core because the core is redundant.

### CODE REVIEW

**Comment by jrgnicho** [comment]
Thanks for creating this PR, I'll review it tomorrow

**Comment by jrgnicho** [comment]
@Levi-Armstrong this looks good to me, did you build this in melodic or noetic?  It may make sense to create a noetic-devel branch and merge these changes there instead

**Review by jrgnicho — APPROVED** [review]
Looks good to me

**Comment by Levi-Armstrong** [comment]
@jrgnicho Did you want to merge this into this branch?

**Comment by jrgnicho** [comment]
@Levi-Armstrong let me make sure that the moveit repository isn't currently using the melodic devel branch.

**Pull request merged**
