### PR TITLE
Collision Avoidance code for UR5 robotic arm

### PR DESCRIPTION
**Pull request by addy1997**
Hello folks,

This code is about motion planning with collision avoidance incorporated with STOMP. I would like anyone to try it out. 
I will be really thankful for feedback on working.

Thanks

### CODE REVIEW

**Comment by jrgnicho** [comment]
Are you wanting to merge this?  If so I would recommend placing it in the [ industrial moveit repo](https://github.com/ros-industrial/industrial_moveit/tree/melodic-devel/industrial_moveit_benchmarking) and would be nice if you could add a link in the readme to that demo if you end up creating it there.

**Comment by addy1997** [comment]
> Are you wanting to merge this? If so I would recommend placing it in the [ industrial moveit repo](https://github.com/ros-industrial/industrial_moveit/tree/melodic-devel/industrial_moveit_benchmarking) and would be nice if you could add a link in the readme to that demo if you end up creating it there.

Yes I want to merge this with the repo.

**Comment by jrgnicho** [comment]
based on the title of the PR, this demo program seems to be specific to the UR5 which means that this repository would have to depend on the UR repos to work.  Furthermore, the code doesn't really have anything that's stomp specific as it calls the motion planning pipeline through moveit.

**Comment by addy1997** [comment]
> based on the title of the PR, this demo program seems to be specific to the UR5 which means that this repository would have to depend on the UR repos to work. Furthermore, the code doesn't really have anything that's stomp specific as it calls the motion planning pipeline through moveit.

Actually, I am sorry to name it wrongly it is not based on stomp. I works well with OMPL.

**Comment by addy1997** [comment]
The code is not intended for UR5 only but can be used with any
moveit-supported robot.

**Comment by jrgnicho** [comment]
Nevertheless, the goal position is specific to some urdf so it won't work on any robot. I don't think it makes sense for this demo program to be in this repo

**Comment by addy1997** [comment]
so should i make a pull up request to the other repo u mentioned?

**Pull request closed without merging**
